// import React from 'react'

// const 2 = () => {
//   return (
//        <group dispose={null}>
//         <group>
//           <mesh
//             geometry={nodes["Circle001_engine_0"].geometry}
//             material={materials["engine"]}
//           />
//           <mesh
//             geometry={nodes["Circle002_engine_0"].geometry}
//             material={materials["engine"]}
//           />
//           <mesh
//             geometry={nodes["Circle003_engine_0"].geometry}
//             material={materials["engine"]}
//           />
//           <mesh
//             geometry={nodes["Circle004_engine_0"].geometry}
//             material={materials["engine"]}
//           />
//           <mesh
//             geometry={nodes["Circle005_engine_0"].geometry}
//             material={materials["engine"]}
//           />
//           <mesh
//             geometry={nodes["Circle006_engine_0"].geometry}
//             material={materials["engine"]}
//           />
//           <mesh
//             geometry={nodes["Circle007_engine_0"].geometry}
//             material={materials["engine"]}
//           />
//           <mesh
//             geometry={nodes["Circle008_engine_0"].geometry}
//             material={materials["engine"]}
//           />
//           <mesh
//             geometry={nodes["Circle009_engine_0"].geometry}
//             material={materials["engine"]}
//           />
//           <mesh
//             geometry={nodes["Circle_body_black_0"].geometry}
//             material={materials["body_black"]}
//           />
//         </group>

// <group>
//           <mesh
//             geometry={nodes["Cube002_details_0"].geometry}
//             material={materials["details"]}
//           />
//           <mesh
//             geometry={nodes["Cube004_fins_0"].geometry}
//             material={materials["fins"]}
//           />
//           <mesh
//             geometry={nodes["Cube_details_0"].geometry}
//             material={materials["details"]}
//           />
//     </group>


//         <group>
//           <mesh
//             geometry={nodes["Cylinder001_fairing_0"].geometry}
//             material={materials["fairing"]}
//           />
//           <mesh
//             geometry={nodes["Cylinder_body_0"].geometry}
//             material={materials["body"]}
//           />
//           <mesh
//             geometry={nodes["Cylinder_body_black_0"].geometry}
//             material={materials["body_black"]}
//           />
//         </group>



//         <group>
//           <mesh
//             geometry={nodes["Plane002_details_0"].geometry}
//             material={materials["details"]}
//           />
//           <mesh
//             geometry={nodes["Plane003_details_0"].geometry}
//             material={materials["details"]}
//           />
//           <mesh
//             geometry={nodes["Plane004_details_0"].geometry}
//             material={materials["details"]}
//           />
//           <mesh
//             geometry={nodes["Plane005_details_0"].geometry}
//             material={materials["details"]}
//           />
//           <mesh
//             geometry={nodes["Plane006_details_0"].geometry}
//             material={materials["details"]}
//           />
//           <mesh
//             geometry={nodes["Plane007_details_0"].geometry}
//             material={materials["details"]}
//           />
//           <mesh
//             geometry={nodes["Plane008_details_0"].geometry}
//             material={materials["details"]}
//           />

//           <mesh
//             geometry={nodes["Plane009_legs_0"].geometry}
//             material={materials["legs"]}
//           />
//           <mesh
//             geometry={nodes["Plane010_legs_0"].geometry}
//             material={materials["legs"]}
//           />
//           <mesh
//             geometry={nodes["Plane011_legs_0"].geometry}
//             material={materials["legs"]}
//           />
//           <mesh
//             geometry={nodes["Plane012_legs_0"].geometry}
//             material={materials["legs"]}
//           />
//           <mesh
//             geometry={nodes["Plane013_legs_0"].geometry}
//             material={materials["legs"]}
//           /> 
//           <mesh
//             geometry={nodes["Plane014_details_0"].geometry}
//             material={materials["details"]}
//           />
//           <mesh
//             geometry={nodes["Plane015_details_0"].geometry}
//             material={materials["details"]}
//           />
//           <mesh
//             geometry={nodes["Plane016_details_0"].geometry}
//             material={materials["details"]}
//           />
//           <mesh
//             geometry={nodes["Plane_details_0"].geometry}
//             material={materials["details"]}
//           />
//         </group>
//       </group>
//   )
// }

// export default 2